CREATE TABLE GOODS_INFO(
GINUM INT AUTO_INCREMENT PRIMARY KEY,
GINAME VARCHAR(200) NOT NULL,
GIDESC VARCHAR(300) NOT NULL,
VINUM INT NOT NULL,
GICREDAT VARCHAR(8) NOT NULL,
GICRETIM VARCHAR(6) NOT NULL);