
CREATE TABLE VENDOR_INFO(
VINUM INT AUTO_INCREMENT PRIMARY KEY,
VINAME VARCHAR(200) NOT NULL,
VIDESC VARCHAR(300) NOT NULL,
VIADDRESS VARCHAR(300) NOT NULL,
VIPHONE VARCHAR(20) NOT NULL,
VICREDAT VARCHAR(8) NOT NULL,
VICRETIM VARCHAR(6) NOT NULL);

select DATE_FORMAT(NOW(),'%Y%m%d');
select DATE_FORMAT(NOW(),'%H%i%s');